### ISSUE TITLE
Установить OTRS

### ISSUE THREAD

**Issue by perchits** [ultra-sw/its#1]
Установить OTRS  и сделать его доступным для членов команды

**Comment by fintnovo** [comment]
Сделано.
Заведены доступы для программистов (ПАРОЛИ НАДО СМЕНИТЬ!):
Вход в агентский интерфейс (специалиста техподдержки) по адресу : it.nvrs.net:7777/otrs/index.pl 
Логин - Ваш E-Mail 
Пароль - 12345
Вход в клиентский интерфейс (специалиста техподдержки) по адресу : it.nvrs.net:7777/otrs/customer.pl 
Логин - client@integral-info.ru 
Пароль - 12345
